#!/usr/bin/env bash
# Install the ib-agent CLI, its man page and its Kiro skill for the current user.
#
# What this creates:
#   ~/.local/bin/ib-agent                     wrapper: read-only pinned, audited
#   ~/.local/share/man/man1/ib-agent.1        symlink to man/ib-agent.1
#   ~/.kiro/skills/ib-agent/SKILL.md          symlink to .kiro/skills/...
#
# Symlinks are used for the man page and the skill so the repository stays the
# single source of truth: editing the repo updates the installed copies.
#
# Idempotent. Run again after pulling changes.

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_DIR="${HOME}/.local/bin"
MAN_DIR="${HOME}/.local/share/man/man1"
KIRO_SKILL_DIR="${HOME}/.kiro/skills/ib-agent"

VENV_BIN="${PROJECT_ROOT}/.venv/bin/ib-agent"

say()  { printf '%s\n' "$*"; }
warn() { printf 'warning: %s\n' "$*" >&2; }
die()  { printf 'error: %s\n' "$*" >&2; exit 1; }

# --- preconditions ---------------------------------------------------------

[ -d "${PROJECT_ROOT}/src/ib_agent" ] || die "not an ib_agent checkout: ${PROJECT_ROOT}"

if [ ! -x "${VENV_BIN}" ]; then
    warn "${VENV_BIN} missing; running 'uv sync'"
    command -v uv >/dev/null 2>&1 || die "uv not found; install uv or run 'uv sync' manually"
    (cd "${PROJECT_ROOT}" && uv sync)
fi
[ -x "${VENV_BIN}" ] || die "still no ${VENV_BIN} after uv sync"

mkdir -p "${BIN_DIR}" "${MAN_DIR}" "${KIRO_SKILL_DIR}"

# --- 1. the wrapper --------------------------------------------------------
#
# Why a wrapper rather than a symlink to the venv entry point:
#   * it pins IB_READONLY=true, so no caller can flip the client-side gate by
#     exporting an environment variable;
#   * it appends one audit line per invocation, so there is a record of which
#     consumer asked for what;
#   * it gives every invocation its own client id, so concurrent callers do not
#     collide on the Gateway's single-session-per-client-id rule;
#   * it is cwd-independent: settings still load from the project's .env.

cat > "${BIN_DIR}/ib-agent" <<WRAPPER
#!/usr/bin/env bash
# Generated by ${PROJECT_ROOT}/scripts/install-cli.sh - do not edit by hand.
set -uo pipefail

PROJECT_ROOT="${PROJECT_ROOT}"
BIN="${VENV_BIN}"

# Read-only is not negotiable through the environment. Opening this gate is a
# deliberate act that requires editing ~/ibc/config.ini as well, and there is no
# order code in the package regardless.
export IB_READONLY=true

# Distinct client id per invocation. The Gateway allows one session per client
# id; a fixed id makes a background 'watch' and an ad-hoc query fight. Range
# 100-227 keeps clear of the default 17 used by any long-running writer.
if [ -z "\${IB_CLIENT_ID:-}" ]; then
    export IB_CLIENT_ID=\$(( 100 + (\$\$ % 128) ))
fi

# Who is calling. Consumers should set IB_AGENT_PROFILE (e.g. option_harvester)
# so the audit log distinguishes them.
PROFILE="\${IB_AGENT_PROFILE:-\${USER:-unknown}}"
AUDIT_LOG="\${IB_AGENT_AUDIT_LOG:-\${PROJECT_ROOT}/logs/cli-audit.log}"

start=\$SECONDS
"\${BIN}" "\$@"
rc=\$?

mkdir -p "\$(dirname "\${AUDIT_LOG}")" 2>/dev/null || true
printf '%s\tprofile=%s\tpid=%s\trc=%s\tdur=%ss\targv=%s\n' \\
    "\$(date -u +%Y-%m-%dT%H:%M:%SZ)" "\${PROFILE}" "\$\$" "\${rc}" \\
    "\$(( SECONDS - start ))" "\$*" >> "\${AUDIT_LOG}" 2>/dev/null || true

exit \${rc}
WRAPPER
chmod 755 "${BIN_DIR}/ib-agent"
say "installed ${BIN_DIR}/ib-agent"

# --- 2. man page -----------------------------------------------------------

ln -sf "${PROJECT_ROOT}/man/ib-agent.1" "${MAN_DIR}/ib-agent.1"
say "installed ${MAN_DIR}/ib-agent.1 -> ${PROJECT_ROOT}/man/ib-agent.1"

if command -v mandb >/dev/null 2>&1; then
    mandb --quiet "${HOME}/.local/share/man" >/dev/null 2>&1 || true
fi

# --- 3. Kiro skill ---------------------------------------------------------
# Global install, so every workspace (including option_harvester) can load it.

ln -sf "${PROJECT_ROOT}/.kiro/skills/ib-agent/SKILL.md" "${KIRO_SKILL_DIR}/SKILL.md"
say "installed ${KIRO_SKILL_DIR}/SKILL.md -> ${PROJECT_ROOT}/.kiro/skills/ib-agent/SKILL.md"

# --- 4. verify -------------------------------------------------------------

fail=0

if "${BIN_DIR}/ib-agent" --help >/dev/null 2>&1; then
    say "check: wrapper runs"
else
    warn "check: wrapper failed to run"; fail=1
fi

if MANPATH="${HOME}/.local/share/man:${MANPATH:-}" man -w ib-agent >/dev/null 2>&1; then
    say "check: man page resolves"
else
    warn "check: 'man ib-agent' does not resolve yet (see PATH/MANPATH note below)"
fi

if head -1 "${KIRO_SKILL_DIR}/SKILL.md" | grep -q '^---$'; then
    say "check: skill frontmatter present"
else
    warn "check: skill frontmatter missing"; fail=1
fi

# --- 5. shell notes --------------------------------------------------------

case ":${PATH}:" in
    *":${BIN_DIR}:"*) ;;
    *)
        warn "${BIN_DIR} is not on PATH. Add to ~/.bashrc:"
        printf '\n    export PATH="%s:$PATH"\n' "${BIN_DIR}" >&2
        ;;
esac

if ! man -w ib-agent >/dev/null 2>&1; then
    warn "add to ~/.bashrc so 'man ib-agent' works in a fresh shell:"
    printf '\n    export MANPATH="%s:$(manpath 2>/dev/null)"\n' "${HOME}/.local/share/man" >&2
fi

say ""
say "done. Try:  ib-agent status --json  |  man ib-agent"
exit ${fail}
